### ISSUE TITLE
indexing bug using FCD gcamp recording

### ISSUE THREAD

**Issue by gregbubnis** [focolab/gcamp-extractor#13]
I'm trying to run gcamp extractor on one of the FCD gcamp recordings, but there is a bug related to indexing rather deep in the code.

![image](https://user-images.githubusercontent.com/41395248/88211939-49051d80-cc0b-11ea-8d37-10eb4be60532.png)

This commit (805af3d) has an example file ```gcamp-extractor/examples/example_fcd.py``` that should reproduce the bug for others (you will have to reconfigure the filepath for your own system, and have the FCD data on disk).

In this branch, I also had to made a few quick changes to allow compatibility with files that:
- have the .tiff extension (rather than .tif), and
- don't adhere to the 'aaaa-NN.tif' naming scheme with numbers immediately preceding the file extension

halp!

**Comment by RaymondDunn** [comment]
I think this is a different indexing bug from #16 but this has to do with how, if prediction is enabled, blob matching on adjacent timepoints is done based on predicted displacement instead of detected blob positions. not clear to me if this problem is still present after a myriad of fixes by JB

separately i suggest there should be "create working FCD example" kinda like Greg's wormjam for np-gui. then additional issues if necessary. closing this accordingly
