### ISSUE TITLE
Reduce buried parameter defaults

### ISSUE THREAD

**Issue by gregbubnis** [focolab/gcamp-extractor#46]
https://github.com/focolab/gcamp-extractor/blob/b318436c3d933f442ef334edbc78f4fd8b7929cf/gcamp_extractor/Extractor.py#L495

This method has some hard coded defaults (filter kernel sizes, etc) that should, IMO, be resolved upstream. Or resolved in a manner such that whatever parameters are used (whether passed or default) can still be output with the analysis results. An intermediate step could be to explicitly declare all such parameters at the top of the method.

**Comment by RaymondDunn** [comment]
great catch. at the risk of piggybacking, i think there's another important item that's related to this, that has to do with organization/naming of parameters. currently imo it's quite confusing. 

for example, here i've isolated elements the arguments dictionary I submit when i instantiate an Extractor, with comments on param ambiguity:
```
        arguments = {
            ...
            "frames": [ 0, 1,  2, 3, 4, 5, 6, 7, 8, 9,10, 11, ],     # note this is z-planes not frames
            "offset": 0,       # offset refers to time not space
            "t": 10,     # this is how many frames to quantify, so just calling it "t" is silly
            "anisotropy": (11, 1, 1),  
            "gaussian": (3, 0, 1, 0),   # non intuitive param ordering - i expect just two parameters for a gaussian. perhaps a gaussian?
            "median": 3,  # this is a median filter kernel size, not a median 
            "quantile": 0.9631,   # quantile of...? 
            "reg_peak_dist": 10,  # reg here refers to registration, but this param refers to the bipartite mapping done after find_peaks (not a param for the registration step)
            "remove_blobs_dist": 6,   
            "blob_merge_dist_thresh": 6,    # ambiguous with the above param
            "regen": False,    # regen... what?
            "predict": False,    # predict ... what?
            "algorithm": "seeded_tmip_skimage",
            "algorithm_params": {
                "peaks": peaks,
                "labels": labels,
                "window_size": 50,   # window is in t... while below params are in xy. might wanna 
                "min_distance": 12,   # of...?
                "min_filter": 9,  # of...?
                "manage_collisions": "prune",
            },
        }

```

this is a good sign to me as it's a natural consequence of increased sophistication. i'd rate this as a (B) or (C) priority because it's more book keeping, but imo should go along with a refactor.

for comparison, in wb-matlab parameter names are prefixed with the step that they're relevant for.
for example:
* fb_minBlobSpacing refers to the "find blob" (segmentation) step of the alg, and intuitively is a threshold for minimum distance between blobs
* cb_maxTBlobBindingDist refers to the "connect blobs" (blobs --> blob threads) step , and intuitively is a threshold for spatial distance blobs can be threaded through time
* ex_numPixels refers to the "extract" (quantify) step of the alg, and is the number of pixels to quantify

so i suggest a path forward would be to follow this kind of stylizing for param naming

**Comment by gregbubnis** [comment]
I think that everything developed so far conforms to this sequential scheme (with the possibility to bypass some steps): ​
1. drift correction (possibly with its own filtering)
2. image filtering (including one or more of T-MIP generation, gaussian, median, threshold, and template filters)
3. peak detection
4. peak registration across time (incl. infilling dim blobs)
5. signal quantification (extraction)

But yeah, this is subject to larger scale refactoring decisions. IMO the ```BlobThreadTracker.find_peaks()``` method is bundling a whole lot together (many permutations of steps 1-4) and is ripe for refactoring. Drift correction (1) and peak registration across time (4) seem wholly independent of 2-3 and could be split off as far as I can tell. And (5) is already a separate step in the workflow.

So if eventual refactoring does modularize these steps, it raises the question of whether to keep a flat parameter dict (maybe with prefixes) or to nest parameters associated with each step.

Agree it is lower priority.
